# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orderbook.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'orderbook.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0forderbook.proto\"=\n\x18OrderbookSnapshotRequest\x12\x12\n\nsecurityId\x18\x01 \x01(\x05\x12\r\n\x05\x64\x65pth\x18\x02 \x01(\r\"/\n\x0cOrderSummary\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x10\n\x08quantity\x18\x02 \x01(\x01\"|\n\x19OrderbookSnapshotResponse\x12\x1b\n\x04\x62ids\x18\x01 \x03(\x0b\x32\r.OrderSummary\x12\x1b\n\x04\x61sks\x18\x02 \x03(\x0b\x32\r.OrderSummary\x12\x12\n\nsecurityId\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"\x95\x01\n\x0cOrderRequest\x12$\n\x08newOrder\x18\x01 \x01(\x0b\x32\x10.NewOrderRequestH\x00\x12*\n\x0b\x63\x61ncelOrder\x18\x02 \x01(\x0b\x32\x13.CancelOrderRequestH\x00\x12*\n\x0b\x63hangeOrder\x18\x03 \x01(\x0b\x32\x13.ModifyOrderRequestH\x00\x42\x07\n\x05order\"I\n\x10OrderRequestCore\x12\x0f\n\x07orderId\x18\x01 \x01(\x03\x12\x12\n\nsecurityId\x18\x02 \x01(\x05\x12\x10\n\x08username\x18\x03 \x01(\t\"k\n\x0fNewOrderRequest\x12$\n\torderCore\x18\x01 \x01(\x0b\x32\x11.OrderRequestCore\x12\r\n\x05price\x18\x02 \x01(\x03\x12\x10\n\x08quantity\x18\x03 \x01(\r\x12\x11\n\tisBuySide\x18\x04 \x01(\x08\":\n\x12\x43\x61ncelOrderRequest\x12$\n\torderCore\x18\x01 \x01(\x0b\x32\x11.OrderRequestCore\"z\n\x12ModifyOrderRequest\x12$\n\torderCore\x18\x01 \x01(\x0b\x32\x11.OrderRequestCore\x12\x13\n\x0bmodifyPrice\x18\x02 \x01(\x03\x12\x16\n\x0emodifyQuantity\x18\x03 \x01(\r\x12\x11\n\tisBuySide\x18\x04 \x01(\x08\"2\n\rOrderResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x8e\x01\n\x10OrderbookService\x12+\n\nPlaceOrder\x12\r.OrderRequest\x1a\x0e.OrderResponse\x12M\n\x14GetOrderbookSnapshot\x12\x19.OrderbookSnapshotRequest\x1a\x1a.OrderbookSnapshotResponseB\x12\xaa\x02\x0f\x41pi.Grpc.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orderbook_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\017Api.Grpc.Protos'
  _globals['_ORDERBOOKSNAPSHOTREQUEST']._serialized_start=19
  _globals['_ORDERBOOKSNAPSHOTREQUEST']._serialized_end=80
  _globals['_ORDERSUMMARY']._serialized_start=82
  _globals['_ORDERSUMMARY']._serialized_end=129
  _globals['_ORDERBOOKSNAPSHOTRESPONSE']._serialized_start=131
  _globals['_ORDERBOOKSNAPSHOTRESPONSE']._serialized_end=255
  _globals['_ORDERREQUEST']._serialized_start=258
  _globals['_ORDERREQUEST']._serialized_end=407
  _globals['_ORDERREQUESTCORE']._serialized_start=409
  _globals['_ORDERREQUESTCORE']._serialized_end=482
  _globals['_NEWORDERREQUEST']._serialized_start=484
  _globals['_NEWORDERREQUEST']._serialized_end=591
  _globals['_CANCELORDERREQUEST']._serialized_start=593
  _globals['_CANCELORDERREQUEST']._serialized_end=651
  _globals['_MODIFYORDERREQUEST']._serialized_start=653
  _globals['_MODIFYORDERREQUEST']._serialized_end=775
  _globals['_ORDERRESPONSE']._serialized_start=777
  _globals['_ORDERRESPONSE']._serialized_end=827
  _globals['_ORDERBOOKSERVICE']._serialized_start=830
  _globals['_ORDERBOOKSERVICE']._serialized_end=972
# @@protoc_insertion_point(module_scope)
